server:
  port: 12000

spring:
  elasticsearch:
    rest:
      # 逗号分隔的Elasticsearch实例使用的列表
      uris: http://172.16.33.33:9200
      # 链接超时时间
      connection-timeout:
      # 读取超时时间
      read-timeout:
      # ES 用户名
      username:
      # ES 密码
      password:
  application:
    name: layman-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  thymeleaf:
    cache: false


logging:
  level:
    com.liuyang19900520.laymanmall.search: debug
    root: warn
  pattern:
    console: "%d{yyyy-MM-dd} [%thread] - %msg%n"
