server:
  port: 12000
elasticsearch:
  host: 172.16.33.33
  port: 9200
spring:
  application:
    name: layman-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  thymeleaf:
    cache: false


logging:
  level:
    com.liuyang19900520.laymanmall.search: debug
    root: warn
  pattern:
    console: "%d{yyyy-MM-dd} [%thread] - %msg%n"
