#server:
#  port: 10000
#
#spring:
#  datasource:
#    #MySQL配置
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://172.16.33.33:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: root
#  application:
#    name: layman-coupon
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#  thymeleaf:
#    cache: false
#  redis:
#    host: 172.16.33.33
#    port: 6379
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#
#
#
#
#
#
#
#
#
#
#
#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#  mapper-locations: classpath:/mapper/**/*.xml
#logging:
#  level:
#    com.bigdata.gulimall.product: debug
#    root: warn
#  pattern:
#    console: "%d{yyyy-MM-dd} [%thread] - %msg%n"
